### ISSUE TITLE
Potentially incorrect coefficients

### ISSUE THREAD

**Issue by XenonSup** [0aax/mpc#1]
https://github.com/0aax/mpc/blob/e8bca48d5f8d640faf0b4071dba077b7cbdf55a3/casadi_/mpcc/utils.py#L35-L39

In the above lines 
`np.polynomial.polynomial.Polynomial.fit` is used to fit a polynomial and extract polynomial coefficients. However those coefficients are not for any ordinary polynomial as they are fitted to a _shifted and scaled_ polynomial 

```
C[0] + C[1] * ( b + m*x )^1 + ... + C[n] * (b + m*x)^n
# Instead of
C[0] + C[1]     *       x^1 + ... + C[n]     *     x^n
```
as documented  [here](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.fit.html#numpy.polynomial.polynomial.Polynomial.fit) which makes the extracted coefficients ambiguous on their own.
**Is that the intended effect?**

If not (following the recommendation in that documentation) this should be converted to
```
xpoly = np.polynomial.polynomial.Polynomial.fit(tpts, xpts, order)
ypoly = np.polynomial.polynomial.Polynomial.fit(tpts, ypts, order)
cx = xpoly.convert().coef[::-1]
cy = ypoly.convert().coef[::-1]
```

**Comment by 0aax** [comment]
This indeed appears to be a bug. Apologies, I did not realize that the polynomial was shifted and scaled. I will correct the code in the main branch.
